replicaCount: 1

image:
  repository: mirror-svc        # this matches your local image name
  tag: local                    # what you build with docker build -t mirror-svc:local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4004

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: mirror.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

env:
  - name: DB_PATH
    value: /data/mirror.db

volumeMounts:
  - name: data
    mountPath: /data

volumes:
  - name: data
    emptyDir: {}
