{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mirror-svc.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts[0].host }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts[0].paths[0].path }}
            pathType: {{ .Values.ingress.hosts[0].paths[0].pathType }}
            backend:
              service:
                name: {{ include "mirror-svc.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
